"""Fetch motion group models from the NOVA API and generate nova/cell/motion_group_models.py."""

import asyncio
import logging
from pathlib import Path

from nova import Nova

logger = logging.getLogger(__name__)

OUTPUT_PATH = Path(__file__).resolve().parent.parent / "cell" / "motion_group_models.py"


def convert_motion_group_model_string(model: str) -> str:
    """Convert e.g. 'KUKA_KR16_R2010_2' to 'kuka-kr16_r2010_2'.

    The manufacturer prefix (before the first '_') is separated by '-',
    everything is lowercased.
    """
    manufacturer, _, rest = model.partition("_")
    return f"{manufacturer.lower()}-{rest.lower()}"


def generate_enum_source(models: list[str]) -> str:
    INDENT = " " * 4  # based on ruff configuration
    if not models:
        raise ValueError("API returned no models — skipping file generation.")

    values = ",\n".join(
        f'{INDENT}"{convert_motion_group_model_string(model)}"' for model in sorted(models)
    )

    return f"""# AUTO-GENERATED by nova/helper_scripts/create_motion_group_models.py — do not edit manually

from typing import Literal


MotionGroupModel = Literal[
{values},
]
"""


async def update_motion_group_models() -> None:
    async with Nova() as nova:
        models = await nova.api.motion_group_models_api.get_motion_group_models()
        source = generate_enum_source(models)
        OUTPUT_PATH.write_text(source, encoding="utf-8", newline="\n")
        logger.info("Wrote %d models to %s", len(models), OUTPUT_PATH)


if __name__ == "__main__":
    asyncio.run(update_motion_group_models())
