apiVersion: v1
kind: Service
metadata:
  name: {{ include "rerun-nova.fullname" . }}
  labels:
    {{- include "rerun-nova.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
    - port: 9876
      targetPort: 9876
      protocol: TCP
      name: sdk
    - port: 9877
      targetPort: 9877
      protocol: TCP
      name: ws
  selector:
    {{- include "rerun-nova.selectorLabels" . | nindent 4 }}
