appIcon: app_icon.png
containerImage:
  credentials:
    password: ""
    registry: ""
    user: ""
  image: andiikaa/rerun:0.0.5
  secrets:
    - name: pull-secret-registry-1-docker-io
environment: []
name: rerun
port: 3001
