apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: rerun
build:
  artifacts:
    - image: registry.code.wabo.run/ai/rerun-nova/rerun-nova
      context: .
      docker:
        dockerfile: Dockerfile
        buildArgs:
          platform: "linux/amd64"
  local:
    useBuildkit: true
manifests:
  kustomize:
    paths:
      - ./k8s
