from nova import api
from nova.actions.base import Action
from nova.actions.motions import Motion
from nova.core.exceptions import InconsistentCollisionScenes


def compare_collision_setups(setup1: api.models.CollisionSetup, setup2: api.models.CollisionSetup):
    """Return True if two pydantic CollisionSetup models are equal by value.

    Uses model_dump in json mode with exclude_unset/none to avoid differences caused
    by default/unset fields or None values.
    """
    dump1 = setup1.model_dump_json(exclude_unset=True, exclude_none=True)
    dump2 = setup2.model_dump_json(exclude_unset=True, exclude_none=True)
    return dump1 == dump2


def validate_collision_setups(actions: list[Action]) -> list[api.models.CollisionSetup]:
    """
    RAE V1 APIs provide two ways of planning actions.
    Collition free planning and collision checked planning.
    As the names suggest, collision free planning produces a joint trajectory with which the collision is avoided.
    But collision check planning checks for collision and if there is one, it will return an error.


    The action list python sdk takes from the user has a variety of types.
    There can be a variety of actions in the list.
    1. Collision free motions
    2. Normal motions
    3. Waits
    4. Write actions -> this is a special write on the path supported by the API


    This function checks that a given set of actions contains valid collision scenes data.
    It is assumed that the action list provided here is a sub-batch generated by the split_actions_into_batches function.
    """
    motion_count = len([action for action in actions if isinstance(action, Motion)])
    collision_setups = [
        action.collision_setup
        for action in actions
        if isinstance(action, Motion) and action.collision_setup is not None
    ]

    if len(collision_setups) != 0 and len(collision_setups) != motion_count:
        raise InconsistentCollisionScenes(
            "Only some of the actions have collision scene. Either specify it for all or none."
        )

    # If a collision scene is provided, the same should be provided for all the collision scene
    if len(collision_setups) > 1:
        first_setup = collision_setups[0]
        if not all(compare_collision_setups(first_setup, setup) for setup in collision_setups[1:]):
            raise InconsistentCollisionScenes(
                "All actions must use the same collision scene but some are different"
            )

    return collision_setups
