"""Fetch motion group models from the NOVA API and generate nova/cell/motion_group_models.py."""

import asyncio
import logging
from pathlib import Path

from nova import Nova

logger = logging.getLogger(__name__)

OUTPUT_PATH = Path(__file__).resolve().parent.parent / "nova" / "cell" / "motion_group_models.py"


def to_enum_value(model: str) -> str:
    """Convert e.g. 'KUKA_KR16_R2010_2' to 'kuka-kr16_r2010_2'.

    The manufacturer prefix (before the first '_') is separated by '-',
    everything is lowercased.
    """
    manufacturer, _, rest = model.partition("_")
    return f"{manufacturer.lower()}-{rest.lower()}"


def generate_enum_source(models: list[str]) -> str:
    lines = [
        "# AUTO-GENERATED by scripts/create_motion_group_models.py — do not edit manually",
        "",
        "from enum import StrEnum",
        "",
        "",
        "class MotionGroupModel(StrEnum):",
    ]
    if not models:
        lines.append("\tpass")
        logger.warning("API returned no models — skipping file generation.")
    else:
        for model in sorted(models):
            lines.append(f'\t{model} = "{to_enum_value(model)}"')
    lines.append("")
    return "\n".join(lines)


async def main() -> None:
    async with Nova() as nova:
        models = await nova.api.motion_group_models_api.get_motion_group_models()
        if not models:
            logger.warning("API returned no models — skipping file generation.")
            return
        source = generate_enum_source(models)
        OUTPUT_PATH.write_text(source)
        logger.info("Wrote %d models to %s", len(models), OUTPUT_PATH)


if __name__ == "__main__":
    asyncio.run(main())
