---
name: "[nova] Run integration tests & examples"
on:
  pull_request:
    branches:
      - main
concurrency:
  group: run-examples-workflow
  cancel-in-progress: false
jobs:
  # This job creates a NOVA instance and captures the connection details
  setup-instance:
    runs-on: ubuntu-latest
    outputs:
      portal_stg_host: ${{ steps.create.outputs.portal_stg_host }}
      portal_stg_instance_id: ${{ steps.create.outputs.portal_stg_instance_id }}
      portal_stg_access_token_b64: ${{ steps.create.outputs.portal_stg_access_token_b64 }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Create NOVA instance and capture connection details
        id: create
        env:
          PORTAL_STG_REFRESH_URL: ${{ secrets.PORTAL_STG_REFRESH_URL }}
          PORTAL_STG_REFRESH_CLIENT_ID: ${{ secrets.PORTAL_STG_REFRESH_CLIENT_ID }}
          PORTAL_STG_REFRESH_TOKEN: ${{ secrets.PORTAL_STG_REFRESH_TOKEN }}
          API_VERSION: "v1"
          PROJECT_VERSION: "1.0.0"
          GITHUB_RUN_ID: ${{ github.run_id }}
          INSECURE_CURL: "true"
        run: |
          if ! source ./scripts/create_nova_instance.sh; then
            echo "Failed to create NOVA instance."
            exit 1
          fi
          # expose as job outputs
          echo "Expose"
          echo "portal_stg_host=$PORTAL_STG_HOST" >> "$GITHUB_ENV"
          echo "portal_stg_instance_id=$PORTAL_STG_INSTANCE_ID" >> "$GITHUB_ENV"
          echo "::add-mask::$PORTAL_STG_ACCESS_TOKEN"
          TOKEN_B64="$(printf '%s' "$PORTAL_STG_ACCESS_TOKEN" | base64 -w0)"
          echo "::add-mask::$TOKEN_B64"
          echo "portal_stg_access_token_b64=$TOKEN_B64" >> "$GITHUB_ENV"
          cat $GITHUB_OUTPUT
  # This job runs the integration tests and examples
  test-integration:
    runs-on: ubuntu-latest
    needs: setup-instance
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
          # single entry for the whole integration‑test batch
          - id: integration
            run_cmd: "pytest -rs -v -m integration"
          # each example gets its own matrix entry
          - id: 01_basic
            run_cmd: "python examples/01_basic.py"
          - id: 02_plan_and_execute
            run_cmd: "python examples/02_plan_and_execute.py"
          - id: 03_move_and_set_ios
            run_cmd: "python examples/03_move_and_set_ios.py"
          - id: 04_move_multiple_robots
            run_cmd: "python examples/04_move_multiple_robots.py"
          - id: 05_selection_motion_group_activation
            run_cmd: "python examples/05_selection_motion_group_activation.py"
          - id: 06_api_usage
            run_cmd: "python examples/06_api_usage.py"
          - id: 08_multi_step_movement_with_collision_free
            run_cmd: "python examples/08_multi_step_movement_with_collision_free.py"
          - id: 14_welding_example
            run_cmd: "python nova_rerun_bridge/examples/14_welding_example.py"
    env:
      NOVA_API: ${{ needs.setup-instance.outputs.portal_stg_host }}
      NOVA_ACCESS_TOKEN_B64: ${{ needs.setup-instance.outputs.portal_stg_access_token_b64 }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Set up Python environment
        run: |
          pip install uv
          uv sync --extra "nova-rerun-bridge"
      - name: "Run ${{ matrix.id }} suite"
        run: |
          NOVA_ACCESS_TOKEN="$(echo "$NOVA_ACCESS_TOKEN_B64" | base64 -d)"
          echo "DEBUG: decoded token length = ${#NOVA_ACCESS_TOKEN}"
          [[ -z "${NOVA_ACCESS_TOKEN}" ]] && {
            echo "❌ NOVA_ACCESS_TOKEN is empty. Aborting."; exit 1; }

          # generic retry wrapper for *all* commands
          n=0; max=3
          until [ "$n" -ge "$max" ]; do
            echo -e "\nAttempt $((n+1))/$max : ${{ matrix.run_cmd }}"
            if PYTHONPATH=. NOVA_API=$NOVA_API NOVA_ACCESS_TOKEN=$NOVA_ACCESS_TOKEN uv run ${{ matrix.run_cmd }}; then
              echo "Succeeded on attempt $((n+1))"
              break
            fi
            n=$((n+1))
            echo "Retrying in 5 s…"; sleep 5
          done
          if [ "$n" -ge "$max" ]; then
            echo "Command failed after $max attempts." >&2
            exit 1
          fi
      - name: Download diagnose package
        if: failure()
        run: |
          echo "Attempting to fetch the diagnosis package…"
          curl --fail -s -X GET \
            "https://${PORTAL_STG_HOST}/api/v1/internal/system/diagnosis-package/zip" \
            -H 'Accept: application/zip' \
            -H "Authorization: Bearer ${PORTAL_STG_ACCESS_TOKEN}" \
            -o "diagnose-${{ github.run_id }}.zip"
      - name: Upload diagnose artifact
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: diagnose-package
          path: diagnose-${{ github.run_id }}.zip
  # This job cleans up the NOVA instance
  cleanup-instance:
    if: always()
    needs: [setup-instance, test-integration]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cleanup – Delete instance
        run: ./scripts/delete_nova_instance.sh
        env:
          PORTAL_STG_INSTANCE_ID: ${{ needs.setup-instance.outputs.portal_stg_instance_id }}
          PORTAL_STG_ACCESS_TOKEN: ${{ needs.setup-instance.outputs.portal_stg_access_token }}
