---
name: "VSCode Extension: Typecheck, Lint and Format"
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PIP_CACHE_DIR: ${{ github.workspace }}/.cache/pip
    defaults:
      run:
        working-directory: ./vscode-ext/
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: vscode-ext/package.json
      - name: Install dependencies
        run: pnpm install
      - name: Format
        run: pnpm run format
      - name: Lint
        run: pnpm run lint
      - name: Compile tests
        run: pnpm run test:compile
      - name: Build
        run: pnpm run build
