---
name: "VSCode Extension: Typecheck, Lint and Format"
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PIP_CACHE_DIR: ${{ github.workspace }}/.cache/pip
    defaults:
      run:
        working-directory: ./vscode-ext/
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
      - name: Install dependencies
        run: npm install
      - name: Format
        run: npm run format
      - name: Lint
        run: npm run lint
      - name: Unit tests
        run: npm run test:unit
      - name: Build
        run: npm run package
